version: '3.7'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend-container
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    container_name: postgres-container
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    ports:
      - 8080:8080
    depends_on:
      - backend
