apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-app-container1
        image: httpd
        ports:
        - containerPort: 80
